resources:
  projectroot: /opt/vlls/vlls-front/src/

spring:
  jpa:
    show-sql: true
  datasource:
    username: "root"
    password: "root"
    url: "jdbc:mysql://localhost:3306/vlls?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true"
    driverClassName: "com.mysql.jdbc.Driver"
  enviDatasource:
    url: "jdbc:sqlite:./dict/en-vi/anh_viet.db"
  vienDatasource:
    url: "jdbc:sqlite:./dict/vi-en/viet_anh.db"

vlls:
  fb:
    id: "553981174731375"
    secret: "672e475a0e226cbcee223d5d6f342557"
    redirect_uri: "http://www.vlls.ga/vlls-back/security/fb-oauth"
    access_token_uri: "https://graph.facebook.com/oauth/access_token"
    graph_uri: "https://graph.facebook.com/v2.1/me"
    fql_uri: "https://api.facebook.com/method/fql.query"
  mail:
    smtp:
      auth: true
      starttls.enable: true
    server:
      host: "smtp.gmail.com"
      port: 587
      username: "fpt.cp.vls@gmail.com"
      password: "slv.pc.tpf"
      fromEmail: "fpt.cp.vls@gmail.com"
      fromAlias: "Virtual Language Learning System"
  file:
    en:
      audio:
        location: "/opt/vlls/vlls-front/src/assets/audio/en"
    item:
      audio:
        location: "/opt/vlls/vlls-front/src/assets/audio/item"
      img:
        location: "/opt/vlls/vlls-front/src/assets/img/item"
    avatar:
      img:
        location: "/opt/vlls/vlls-front/src/assets/img/avatar"

logging:
  file: "/var/log/vlls/vlls.log"